# Generated by Django 3.2.12 on 2022-12-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_repairservices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='owner',
            field=models.ForeignKey(default=-2020, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='base.user'),
            preserve_default=False,
        ),
    ]
