# Generated by Django 3.2.12 on 2022-12-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rentals_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='rent_status',
        ),
        migrations.AddField(
            model_name='bike',
            name='rent_status',
            field=models.CharField(default=-2020, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentals',
            name='date_of_renting',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
